DROP TABLE IF EXISTS /*TABLE_PREFIX*/t_user_rating_ur;
CREATE TABLE /*TABLE_PREFIX*/t_user_rating_ur (
i_rating_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
fk_i_user_id INT(10),
s_user_email VARCHAR(100),
fk_i_from_user_id INT(10),
i_cat0 INT(1) DEFAULT NULL,
i_cat1 INT(1) DEFAULT NULL,
i_cat2 INT(1) DEFAULT NULL,
i_cat3 INT(1) DEFAULT NULL,
i_cat4 INT(1) DEFAULT NULL,
i_cat5 INT(1) DEFAULT NULL,
i_validate INT(1) DEFAULT 0,
s_comment VARCHAR(5000),
i_type INT(1) DEFAULT 0,
d_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

PRIMARY KEY (i_rating_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET 'UTF8' COLLATE 'UTF8_GENERAL_CI';
