DROP TABLE IF EXISTS /*TABLE_PREFIX*/t_ba_advert;
CREATE TABLE /*TABLE_PREFIX*/t_ba_advert (
pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
fk_s_banner_id VARCHAR(500),
i_type INT(1),
s_name VARCHAR(100),
s_key VARCHAR(100),
s_url VARCHAR(500),
s_code VARCHAR(5000),
s_image VARCHAR(100),
i_views INT(10) DEFAULT 0,
i_clicks INT(10) DEFAULT 0,
d_price_click DECIMAL(10, 3) DEFAULT 0,
d_price_view DECIMAL(10, 3) DEFAULT 0,
d_budget DECIMAL(10, 3) DEFAULT 0,
dt_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
dt_expire DATE,
s_category VARCHAR(100),
s_size_width VARCHAR(10),
s_size_height VARCHAR(10),

PRIMARY KEY (pk_i_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET 'UTF8' COLLATE 'UTF8_GENERAL_CI';



DROP TABLE IF EXISTS /*TABLE_PREFIX*/t_ba_banner;
CREATE TABLE /*TABLE_PREFIX*/t_ba_banner (
pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
s_name VARCHAR(100),
i_type INT,
s_hook VARCHAR(500),

PRIMARY KEY (pk_i_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET 'UTF8' COLLATE 'UTF8_GENERAL_CI';