SET FOREIGN_KEY_CHECKS=0;


ALTER TABLE /*TABLE_PREFIX*/t_osp_user_group ADD i_max_items INT DEFAULT 10;
ALTER TABLE /*TABLE_PREFIX*/t_osp_user_group ADD i_max_items_days INT DEFAULT 30;


DROP TABLE IF EXISTS /*TABLE_PREFIX*/t_osp_pending;
CREATE TABLE /*TABLE_PREFIX*/t_osp_pending (
  pk_i_id INT NOT NULL AUTO_INCREMENT,
  s_transaction_id VARCHAR(100) NULL,
  fk_i_user_id INT NULL,
  s_email VARCHAR(100) NULL,
  s_extra VARCHAR(5000) NULL,
  s_source VARCHAR(20) NULL,
  dt_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY(pk_i_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET 'UTF8' COLLATE 'UTF8_GENERAL_CI';



SET FOREIGN_KEY_CHECKS=1;